version: '3'
services:
  db_event_bot:
    image: postgres
    container_name: db_event_bot
    ports:
      - "2345:5432"
    env_file:
      - .env
    restart: on-failure

  event_bot_user_service:
    container_name: event_bot_user_service
    build:
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "8000:8082"
    depends_on:
      - db_event_bot
    env_file:
      - .env
    restart: on-failure