# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groupService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12groupService.proto\x12\x18\x63om.project.groupService\"*\n\rGroupResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\"\x1f\n\x0cGroupRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\x03\"\"\n\x11GroupTitleRequest\x12\r\n\x05title\x18\x01 \x01(\t2\xdd\x01\n\x0cGroupService\x12\x64\n\x11getGroupByGroupId\x12&.com.project.groupService.GroupRequest\x1a\'.com.project.groupService.GroupResponse\x12g\n\x0fgetGroupByTitle\x12+.com.project.groupService.GroupTitleRequest\x1a\'.com.project.groupService.GroupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groupService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GROUPRESPONSE']._serialized_start=48
  _globals['_GROUPRESPONSE']._serialized_end=90
  _globals['_GROUPREQUEST']._serialized_start=92
  _globals['_GROUPREQUEST']._serialized_end=123
  _globals['_GROUPTITLEREQUEST']._serialized_start=125
  _globals['_GROUPTITLEREQUEST']._serialized_end=159
  _globals['_GROUPSERVICE']._serialized_start=162
  _globals['_GROUPSERVICE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
