# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduleService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scheduleService.proto\x12\x1b\x63om.project.scheduleService\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n\x0fScheduleRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\x03\"\xe2\x01\n\x10ScheduleResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07teacher\x18\x03 \x01(\t\x12\x12\n\nauditorium\x18\x04 \x01(\t\x12-\n\ttimeStart\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07timeEnd\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08weekType\x18\x07 \x01(\t\x12\x0f\n\x07\x64\x61yType\x18\x08 \x01(\t\x12\x0f\n\x07groupId\x18\t \x01(\x03\x32\xec\x02\n\x0fScheduleService\x12t\n\x13getScheduleTomorrow\x12,.com.project.scheduleService.ScheduleRequest\x1a-.com.project.scheduleService.ScheduleResponse0\x01\x12q\n\x10getScheduleToday\x12,.com.project.scheduleService.ScheduleRequest\x1a-.com.project.scheduleService.ScheduleResponse0\x01\x12p\n\x0fgetScheduleWeek\x12,.com.project.scheduleService.ScheduleRequest\x1a-.com.project.scheduleService.ScheduleResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduleService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SCHEDULEREQUEST']._serialized_start=87
  _globals['_SCHEDULEREQUEST']._serialized_end=121
  _globals['_SCHEDULERESPONSE']._serialized_start=124
  _globals['_SCHEDULERESPONSE']._serialized_end=350
  _globals['_SCHEDULESERVICE']._serialized_start=353
  _globals['_SCHEDULESERVICE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
