# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: studentService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14studentService.proto\x12\x1a\x63om.project.studentService\",\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\"c\n\x0fStudentResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x12\n\npatronymic\x18\x04 \x01(\t\x12\x11\n\tgroupName\x18\x05 \x01(\t\"#\n\x0eStudentRequest\x12\x11\n\tstudentId\x18\x01 \x01(\x03\"\x1f\n\x0cGroupRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\x03\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xc7\x03\n\x0eStudentService\x12j\n\x12getUserByStudentId\x12*.com.project.studentService.StudentRequest\x1a(.com.project.studentService.UserResponse\x12r\n\x1agetStudentsChatIdByGroupId\x12(.com.project.studentService.GroupRequest\x1a(.com.project.studentService.UserResponse0\x01\x12i\n\x0egetStudentById\x12*.com.project.studentService.StudentRequest\x1a+.com.project.studentService.StudentResponse\x12j\n\x12getStudentByUserId\x12\'.com.project.studentService.UserRequest\x1a+.com.project.studentService.StudentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'studentService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERRESPONSE']._serialized_start=52
  _globals['_USERRESPONSE']._serialized_end=96
  _globals['_STUDENTRESPONSE']._serialized_start=98
  _globals['_STUDENTRESPONSE']._serialized_end=197
  _globals['_STUDENTREQUEST']._serialized_start=199
  _globals['_STUDENTREQUEST']._serialized_end=234
  _globals['_GROUPREQUEST']._serialized_start=236
  _globals['_GROUPREQUEST']._serialized_end=267
  _globals['_USERREQUEST']._serialized_start=269
  _globals['_USERREQUEST']._serialized_end=294
  _globals['_STUDENTSERVICE']._serialized_start=297
  _globals['_STUDENTSERVICE']._serialized_end=752
# @@protoc_insertion_point(module_scope)
