# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11userService.proto\x12\x17\x63om.project.userService\":\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32i\n\x0bUserService\x12Z\n\x0bgetUserById\x12$.com.project.userService.UserRequest\x1a%.com.project.userService.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERRESPONSE']._serialized_start=46
  _globals['_USERRESPONSE']._serialized_end=104
  _globals['_USERREQUEST']._serialized_start=106
  _globals['_USERREQUEST']._serialized_end=131
  _globals['_USERSERVICE']._serialized_start=133
  _globals['_USERSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
