# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12user_service.proto\x12\x0cuser_service\"=\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\" \n\x0cGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x32\x9c\x01\n\x0bUserService\x12@\n\x07getUser\x12\x19.user_service.UserRequest\x1a\x1a.user_service.UserResponse\x12K\n\x0fgetUsersByGroup\x12\x1a.user_service.GroupRequest\x1a\x1a.user_service.UserResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_USERRESPONSE']._serialized_start = 36
    _globals['_USERRESPONSE']._serialized_end = 97
    _globals['_USERREQUEST']._serialized_start = 99
    _globals['_USERREQUEST']._serialized_end = 129
    _globals['_GROUPREQUEST']._serialized_start = 131
    _globals['_GROUPREQUEST']._serialized_end = 163
    _globals['_USERSERVICE']._serialized_start = 166
    _globals['_USERSERVICE']._serialized_end = 322
# @@protoc_insertion_point(module_scope)
